### ISSUE TITLE
Ошибка при запуске проекта в докере - Exited(139)

### ISSUE THREAD

**Issue by Zilo676** [CryptoPro/DotnetCoreSampleProject#4]
Здравствуйте.

Пытаюсь запустить тестовый проект в докере, но получаю 139 ошибку. Билд проходит успешно,и при этом сама ошибка появляется непосредственно при запуске проекта при вызове данной строки: 
```csharp
using (var gostCert = new X509Certificate2(Gost2012_256Pfx, "1", X509KeyStorageFlags.CspNoPersistKeySet))
```
Вывод команды `dotnet --info`:
```
root@4ebe19d68823:/app# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.415
 Commit:    52a108342e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.415/

Host (useful for support):
  Version: 3.1.21
  Commit:  df8abc0f7e

.NET Core SDKs installed:
  3.1.415 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
`/opt/cprocsp/bin/amd64/csptestf -enum -info`
```root@4ebe19d68823:/app# /opt/cprocsp/bin/amd64/csptestf -enum -info
CSP (Type:80) v5.0.10003 KC1 Release Ver:5.0.11455 OS:Linux CPU:AMD64 FastCode:READY:AVX.
CryptAcquireContext succeeded.HCRYPTPROV: 37715443
GetProvParam(...PP_ENUMALGS...) until it returns false
   Algid    Bits     Type     NameLen    AlgName
__________________________________________________
 0000661eh  256    Encrypt       14    GOST 28147-89
 00008021h  256    Hash          18    GR 34.11-2012 256
 00002e49h  512    Signature     18    GR 34.10-2012 256
 0000aa46h  512    Exchange      18    DH 34.10-2012 256
 0000aa47h  512    Exchange      18    DH 34.10-2012 256
 0000801fh  32     Hash          18    GOST 28147-89 MAC
 00008034h  256    Hash          20    GR34.11-12 256 HMAC
Cycle exit when getting data. 7 items found. Level completed without problems.
```

Dockerfile:

```dockerfile
FROM mcr.microsoft.com/dotnet/nightly/sdk:3.1-bullseye

# установка рантайма
RUN wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb

RUN apt-get update \
 && apt-get install -y apt-transport-https \ 
 && apt-get update &&  apt-get install -y dotnet-runtime-3.1

ENV DOTNET_MULTILEVEL_LOOKUP=0

# установка пакетов криптопро
COPY ./linux-amd64_deb.tgz ./linux-amd64_deb.tgz
RUN tar -xf ./linux-amd64_deb.tgz
RUN cd ./linux-amd64_deb \
  && chmod +x ./install.sh \
  && ./install.sh

WORKDIR /package_linux_debug
COPY ./package_linux_debug/ ./

WORKDIR /runtime-debug-linux
COPY ./runtime-debug-linux  ./

RUN apt-get install git --no-install-recommends -y 

WORKDIR /
COPY ./NuGet.Config /root/.nuget/NuGet

RUN git clone https://github.com/CryptoProLLC/NetStandard.Library
RUN mkdir -p ~/.nuget/packages/netstandard.library
RUN cp -r ./NetStandard.Library/nugetReady/netstandard.library ~/.nuget/packages/

WORKDIR /app
COPY ./NuGet.Config ./NuGet.Config
COPY ./DotnetCoreSampleProject ./

# RUN dotnet restore "DotnetSampleProject.csproj" --configfile ./NuGet.Config
RUN dotnet restore "DotnetSampleProject.csproj" 
RUN dotnet build "DotnetSampleProject.csproj" -c Debug

CMD ["dotnet", "run"]

```
`DotnetSampleProject.csproj`:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	<RuntimeFrameworkVersion>3.1.3</RuntimeFrameworkVersion>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <!-- make self-contained -->
    <PackageConflictPreferredPackages>Microsoft.Private.CoreFx.NETCoreApp;runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp;$(PackageConflictPreferredPackages)</PackageConflictPreferredPackages>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.Private.CoreFx.NETCoreApp" Version="4.7.0-dev.21370.1" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="System.Security.Cryptography.Pkcs">
        <HintPath>/runtime-debug-linux/System.Security.Cryptography.Pkcs.dll</HintPath>
      </Reference>
      <Reference Include="System.Security.Cryptography.Xml">
        <HintPath>/runtime-debug-linux/System.Security.Cryptography.Xml.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
```

`NuGet.config`:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="local coreclr" value="/package_linux_debug/" />
    <!-- <add key="local coreclr" value="../package_linux_debug" /> -->
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```
![image](https://user-images.githubusercontent.com/24392508/146041815-c19b0610-74e1-423f-ab1a-18501d9e0e52.png)

Можете, пожалуйста, подсказать в чем может быть проблема?

**Comment by Fasjeit** [comment]
Добрый день.

Насколько я понимаю ошибка 139 кидается именно докером, и означает в общем случае "что то пошло не так".  Сам дотнет к этому коду отношения не имеет, но может вызывать такую ошибку.

Нужно выяснить, какую именно ошибку выбрасывает дотнет (посмотреть логи докера, если такие есть, или попробовать их собрать).

**Comment by Zilo676** [comment]
В этом и проблема что сам дотнет не выплевывает какие-либо ошибки, другими словами логи пустые. После того как я поменял версию криптопро с пятой на четвертую и изменил образ на дебиан 9 то смог получить вот такую ошибку:  

```
System.EntryPointNotFoundException: Unable to find an entry point named 'CryptQueryObject' in shared library 'libcapi20'.
   at Interop.crypt32.CryptQueryObject(CertQueryObjectType dwObjectType, Void* pvObject, ExpectedContentTypeFlags dwExpectedContentTypeFlags, ExpectedFormatTypeFlags dwExpectedFormatTypeFlags, Int32 dwFlags, CertEncodingType& pdwMsgAndCertEncodingType, ContentType& pdwContentType, FormatType& pdwFormatType, SafeCertStoreHandle& phCertStore, SafeCryptMsgHandle& phMsg, SafeCertContextHandle& ppvContext)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at DotnetSample.Program.Main(String[] args) in /app/Program.cs:line 73
```

где 73 строка это `var gostCertTest = new X509Certificate2(Gost2012_256Pfx, "1", X509KeyStorageFlags.CspNoPersistKeySet);`

новый докер файл:

```dockerfile
FROM debian:stretch

RUN apt-get update \ 
 && apt-get install -y wget gpg apt-transport-https ca-certificates

# установка рантайма для debian 9
RUN wget -O - https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg \
    && mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ \
    && wget https://packages.microsoft.com/config/debian/9/prod.list \ 
    && mv prod.list /etc/apt/sources.list.d/microsoft-prod.list \
    && chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg \
    && chown root:root /etc/apt/sources.list.d/microsoft-prod.list

RUN apt-get update \
  && apt-get install -y apt-transport-https \
  && apt-get update  \
  && apt-get install -y dotnet-runtime-3.1

RUN apt-get update \
  && apt-get install -y apt-transport-https \
  && apt-get update  \
  && apt-get install -y dotnet-sdk-3.1

ENV DOTNET_MULTILEVEL_LOOKUP=0

# установка пакетов криптопро
COPY ./linux-amd64_deb_4.tgz ./linux-amd64_deb_4.tgz
RUN tar -xf ./linux-amd64_deb_4.tgz
RUN cd ./linux-amd64_deb \
  && chmod +x ./install.sh \
  && ./install.sh

WORKDIR /package_linux_debug
COPY ./package_linux_debug/ ./

WORKDIR /runtime-debug-linux
COPY ./runtime-debug-linux  ./

RUN apt-get install git --no-install-recommends -y 
RUN git config --global http.sslVerify false
RUN git config --global http.postBuffer 1048576000

WORKDIR /
COPY ./NuGet.Config /root/.nuget/NuGet/NuGet.Config

RUN git clone https://github.com/CryptoProLLC/NetStandard.Library
RUN mkdir -p ~/.nuget/packages/netstandard.library
RUN cp -r ./NetStandard.Library/nugetReady/netstandard.library ~/.nuget/packages/

WORKDIR /app
COPY ./DotnetCoreSampleProject ./

RUN dotnet restore "DotnetSampleProject.csproj" 
RUN dotnet build "DotnetSampleProject.csproj" -c Debug

CMD ["dotnet", "run"]
```

`/opt/cprocsp/bin/amd64/csptestf -enum -info`:
```
CSP (Type:80) v4.0.9019 KC1 Release Ver:4.0.9963 OS:Linux CPU:AMD64 FastCode:READY:AVX.
CryptAcquireContext succeeded.HCRYPTPROV: 14296835
GetProvParam(...PP_ENUMALGS...) until it returns false
   Algid    Bits     Type     NameLen    AlgName
__________________________________________________
 0000661eh  256    Encrypt       14    GOST 28147-89
 00008021h  256    Hash          18    GR 34.11-2012 256
 00002e49h  512    Signature     18    GR 34.10-2012 256
 0000aa46h  512    Exchange      18    DH 34.10-2012 256
 0000aa47h  512    Exchange      18    DH 34.10-2012 256
 0000801fh  32     Hash          19    HMAC GOST 28147-89
Cycle exit when getting data. 6 items found. Level completed without problems.
Total: SYS: 0.000 sec USR: 0.000 sec UTC: 0.000 sec
[ErrorCode: 0x00000000]
```

**Comment by Fasjeit** [comment]
Червёртая версия CSP точно работать не будет на Unix, вносили в изменения в CSP специально для dotnet. Ошибка при замене на 4 ожидаемая, не может найти точку входа в функцию, ибо её нет в 4.

Нужна версия CSP не менее 5.0.11823.

**Comment by Zilo676** [comment]
Добавил rsyslog в контейнер чтобы посмотреть системные логи. Вот что получилось достать:

```
root@52e1d4a45f82:/var/log# cat syslog
Dec 16 12:03:55 52e1d4a45f82 rsyslogd: rsyslogd's groupid changed to 102
Dec 16 12:03:55 52e1d4a45f82 rsyslogd: rsyslogd's userid changed to 101
Dec 16 12:03:55 52e1d4a45f82 rsyslogd: [origin software="rsyslogd" swVersion="8.2001.0" x-pid="25" x-info="https://www.rsyslog.com"] start
Dec 16 12:04:04 52e1d4a45f82 DotnetSampleProject: <capi20>CryptDecodeObject!(failed: LastError = 0x80091004)
Dec 16 12:04:04 52e1d4a45f82 DotnetSampleProject: <capi20>CertCreateCertificateContext!failed: LastError = 0x80093000
Dec 16 12:04:04 52e1d4a45f82 DotnetSampleProject: <capi20>CertAddEncodedCertificateToStore!failed: LastError = 0x80093000
```

**Comment by Fasjeit** [comment]
Вне докера проект на целевой машине собирается-запускается?

Если нет - возможная проблема в версиях SDK. Сейчас увы подвязаны на использование конкретных версий SDK, которое указаны в инструкции по сборке. Версии старше лучше удалить..

**Comment by Zilo676** [comment]
Пока что еще не тестировал проект на полноценном хосте с линукс. Проблема еще может быть в том что я использую WSL2 для запуска контейнеров под линукс. Потенциально это может повлиять на работу приложения. Напишу сюда, когда протестирую на хост машине с линуксом.

Смена версии SDK и рантайма не помогли

**Comment by Zilo676** [comment]
Ошибка воспроизводится на хост машине с Linux, при этом билд происходит без ошибок.
Syslog:
```
Dec 24 12:40:13 UbDes01 DotnetSampleProject: <capi20>CryptDecodeObject!(failed: LastError = 0x80091004)
Dec 24 12:40:13 UbDes01 kernel: [105416.395272] DotnetSamplePro[22328]: segfault at 7f066e20cf76 ip 00007f07089aee45 sp 00007fffad114d28 error 4 in libc-2.31.so[7f0708915000+178000]
Dec 24 12:40:13 UbDes01 kernel: [105416.395287] Code: f0 0f 10 5c 16 e0 0f 11 07 0f 11 4f 10 0f 11 54 17 f0 0f 11 5c 17 e0 c3 48 39 f7 0f 87 8c 00 00 00 0f 84 28 ff ff ff 0f 10 26 <0f> 10 6c 16 f0 0f 10 74 16 e0 0f 10 7c 16 d0 44 0f 10 44 16 c0 49
Dec 24 12:40:13 UbDes01 DotnetSampleProject: <capi20>CertCreateCertificateContext!failed: LastError = 0x80093000
Dec 24 12:40:13 UbDes01 DotnetSampleProject: <capi20>CertAddEncodedCertificateToStore!failed: LastError = 0x80093000

```

![image](https://user-images.githubusercontent.com/24392508/147346825-34cb1b66-1ac6-49bf-8812-028689ff14f4.png)

`dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.22
  Commit:  35fa579a30

.NET Core SDKs installed:
  3.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Версию рантайма устанавливаю через .csproj:
```
<RuntimeFrameworkVersion>3.1.3</RuntimeFrameworkVersion>
```

`/opt/cprocsp/bin/amd64/csptestf -enum -info`:
```
CSP (Type:80) v5.0.10003 KC1 Release Ver:5.0.11455 OS:Linux CPU:AMD64 FastCode:READY:AVX.
CryptAcquireContext succeeded.HCRYPTPROV: 14221331
GetProvParam(...PP_ENUMALGS...) until it returns false
   Algid    Bits     Type     NameLen    AlgName
__________________________________________________
 0000661eh  256    Encrypt       14    GOST 28147-89 
 00008021h  256    Hash          18    GR 34.11-2012 256 
 00002e49h  512    Signature     18    GR 34.10-2012 256 
 0000aa46h  512    Exchange      18    DH 34.10-2012 256 
 0000aa47h  512    Exchange      18    DH 34.10-2012 256 
 0000801fh  32     Hash          18    GOST 28147-89 MAC 
 00008034h  256    Hash          20    GR34.11-12 256 HMAC 
Cycle exit when getting data. 7 items found. Level completed without problems.
Total: SYS: 0,000 sec USR: 0,010 sec UTC: 0,000 sec
[ErrorCode: 0x00000000]
```

**Comment by Fasjeit** [comment]
Попробуйте поставить более свежую версию CSP. Как я указывал выше, нужна версия не менее 5.0.11823.
Для тестов на своей машине можно взять пакет установки csp из папки cspTools проекта corefx.

**Comment by Zilo676** [comment]
Да, действительно если установить эту версию то все запускается. Проверил на linux хосте и в докере (win10pro + wsl2 для linux контейнеров). 

Проверил актуальную версию с сайта - `5.0.12330` на ней тоже все работает.
Спасибо за ответы

Issue можно закрывать

**Comment by ComradeSwarog** [comment]
Угу все взлетело на [КриптоПро CSP 5.0 R2](https://cryptopro.ru/products/csp/downloads#latest_csp50r2)
Спасибо за помощь
Но, есть тогда небольшое пожелание для будущих пользователей Libcore - мб добавить предварительную проверку версии CSP, чтобы показывался нормальный stacktrace с описанием ошибки, а не ловить CSP стек в syslog ?)
